databases:
  - name: edawn-db
    plan: free
    databaseName: edawn
    user: edawn

services:
  - type: web
    name: edawn-portal
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn edawn.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: edawn-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,businessbuilders.edawn.org"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com,https://businessbuilders.edawn.org"
      - key: SITE_URL
        value: "https://businessbuilders.edawn.org"
      - key: PYTHON_VERSION
        value: "3.12.3"
