# Generated by Django 5.0.6 on 2026-04-15 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Bootstrap icon class, e.g. bi-star', max_length=50)),
                ('color', models.CharField(default='#008b99', help_text='Hex color for the badge', max_length=7)),
                ('criteria_type', models.CharField(choices=[('visits_completed', 'Visits Completed'), ('contact_attempts', 'Contact Attempts Logged'), ('assignments_received', 'Assignments Received'), ('manual', 'Manually Awarded')], default='manual', max_length=30)),
                ('criteria_value', models.PositiveIntegerField(default=0, help_text='Threshold to auto-award (0 = manual only)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='core.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
