# Generated by Django 5.0.6 on 2026-04-15 15:25

from django.db import migrations


BADGES = [
    {
        'name': 'First Steps',
        'description': 'Received your first company assignment.',
        'icon': 'bi-flag-fill',
        'color': '#6c757d',
        'criteria_type': 'assignments_received',
        'criteria_value': 1,
        'sort_order': 1,
    },
    {
        'name': 'Making Contact',
        'description': 'Logged your first contact attempt.',
        'icon': 'bi-telephone-fill',
        'color': '#0d6efd',
        'criteria_type': 'contact_attempts',
        'criteria_value': 1,
        'sort_order': 2,
    },
    {
        'name': 'Door Knocker',
        'description': 'Logged 10 contact attempts. Persistence pays off!',
        'icon': 'bi-door-open-fill',
        'color': '#6610f2',
        'criteria_type': 'contact_attempts',
        'criteria_value': 10,
        'sort_order': 3,
    },
    {
        'name': 'First Visit',
        'description': 'Completed your first company visit.',
        'icon': 'bi-star-fill',
        'color': '#008b99',
        'criteria_type': 'visits_completed',
        'criteria_value': 1,
        'sort_order': 4,
    },
    {
        'name': 'Road Warrior',
        'description': 'Completed 5 company visits. You\'re on a roll!',
        'icon': 'bi-car-front-fill',
        'color': '#e67e22',
        'criteria_type': 'visits_completed',
        'criteria_value': 5,
        'sort_order': 5,
    },
    {
        'name': 'Ambassador',
        'description': 'Completed 10 company visits. A true EDAWN ambassador!',
        'icon': 'bi-award-fill',
        'color': '#014684',
        'criteria_type': 'visits_completed',
        'criteria_value': 10,
        'sort_order': 6,
    },
    {
        'name': 'Veteran',
        'description': 'Completed 25 company visits. Legendary dedication!',
        'icon': 'bi-shield-fill-check',
        'color': '#198754',
        'criteria_type': 'visits_completed',
        'criteria_value': 25,
        'sort_order': 7,
    },
    {
        'name': 'Legend',
        'description': 'Completed 50 company visits. Hall of fame material!',
        'icon': 'bi-gem',
        'color': '#dc3545',
        'criteria_type': 'visits_completed',
        'criteria_value': 50,
        'sort_order': 8,
    },
]


def seed_badges(apps, schema_editor):
    Badge = apps.get_model('core', 'Badge')
    for data in BADGES:
        Badge.objects.get_or_create(name=data['name'], defaults=data)


def remove_badges(apps, schema_editor):
    Badge = apps.get_model('core', 'Badge')
    Badge.objects.filter(name__in=[b['name'] for b in BADGES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_badge_userbadge_delete_goal'),
    ]

    operations = [
        migrations.RunPython(seed_badges, remove_badges),
    ]
