# Generated by Django 5.0.6 on 2026-04-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_visitnote_expansion_and_lead_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitnote",
            name="additional_contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="visitnote",
            name="additional_contact_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="visitnote",
            name="additional_contact_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="visitnote",
            name="additional_contact_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="visitnote",
            name="at_capacity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unknown"),
                    ("yes", "Yes — at capacity"),
                    ("no", "No — room to grow"),
                ],
                max_length=3,
                verbose_name="At capacity?",
            ),
        ),
        migrations.AddField(
            model_name="visitnote",
            name="building_size_sqft",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Current building size (sq ft)"
            ),
        ),
        migrations.AddField(
            model_name="visitnote",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Contact spoken to"
            ),
        ),
        migrations.AddField(
            model_name="visitnote",
            name="employee_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Current employees"
            ),
        ),
        migrations.AddField(
            model_name="visitnote",
            name="hiring_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hiring", "Actively Hiring"),
                    ("layoffs", "Layoffs Occurring"),
                    ("stable", "Stable / No Change"),
                    ("unknown", "Unknown"),
                ],
                max_length=10,
                verbose_name="Hiring / layoff status",
            ),
        ),
        migrations.AddField(
            model_name="visitnote",
            name="jobs_added_expected",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Expected jobs to be added"
            ),
        ),
        migrations.AddField(
            model_name="visitnote",
            name="jobs_added_last_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Jobs added last year"
            ),
        ),
        migrations.AddField(
            model_name="visitnote",
            name="jobs_lost_last_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Jobs lost last year"
            ),
        ),
        migrations.AddField(
            model_name="visitnote",
            name="volunteer_helped",
            field=models.BooleanField(
                default=False, verbose_name="I helped this company during the visit"
            ),
        ),
        migrations.AddField(
            model_name="visitnote",
            name="volunteer_helped_notes",
            field=models.TextField(blank=True, verbose_name="How did you help?"),
        ),
    ]
