# Generated by Django 5.0.6 on 2026-05-01 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_visitnote_workforce_facility_contact_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitnote",
            name="volunteer_helped",
            field=models.BooleanField(
                default=False,
                verbose_name="I assisted this company with a problem during this visit",
            ),
        ),
        migrations.AlterField(
            model_name="visitnote",
            name="volunteer_helped_notes",
            field=models.TextField(blank=True, verbose_name="How did you assist?"),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("training_completed", models.BooleanField(default=False)),
                ("training_completed_date", models.DateField(blank=True, null=True)),
                ("bbv_certified", models.BooleanField(default=False)),
                ("bbv_certified_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
