# Generated by Django 5.0.6 on 2026-05-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_seed_userprofiles_bbv_badge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "url",
                    models.URLField(help_text="Link to document or external resource"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("visit_script", "Visit Script"),
                            ("snapshot_form", "Company Snapshot Form"),
                            ("workforce_guide", "Workforce Guide"),
                            ("value_prop", "EDAWN Value Prop"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "sort_order", "title"],
            },
        ),
    ]
