# Generated by Django 5.0.6 on 2026-05-01 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_resource_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for direct messages; blank for group board posts",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
