# Generated by Django 5.0.6 on 2026-05-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_assignment_request_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Upload a file (PDF, Word, etc.)",
                upload_to="resources/",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.URLField(
                blank=True, help_text="Link to an external document or resource"
            ),
        ),
    ]
