# Generated by Django 5.0.6 on 2026-05-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_resource_file_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="file",
        ),
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.URLField(help_text="OneDrive or other link to the document"),
        ),
    ]
